---
name: vault-config
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forms\GridField\GridField:
    class: Violet88\VaultModule\GridField\VaultGridField
  Encrypted:
    class: Violet88\VaultModule\FieldType\DBEncrypted
  EncryptedSearch:
    class: Violet88\VaultModule\SearchFilter\EncryptedSearchFilter
  SilverStripe\ORM\DataListFilter:
    properties:
      Encrypted: 'EncryptedSearch'
  SilverStripe\ORM\DataQuery:
    properties:
      Encrypted: 'EncryptedSearch'
  SilverStripe\ORM\DataObject:
    properties:
      Encrypted: 'EncryptedSearch'

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Violet88\VaultModule\SiteConfigExtensions\VaultSiteConfigExtension

Violet88\VaultModule\VaultClient:
  vault_transit_path: 'transit'

# Add the templates folder to the list of folders to look for templates
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - violet88/silverstripe-vault-module
