---
name: vault-config
---
SilverStripe\Core\Injector\Injector:
  Encrypted:
    class: Violet88\VaultModule\FieldType\DBEncrypted

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Violet88\VaultModule\SiteConfigExtensions\VaultSiteConfigExtension
